# General

# Scrollable
set -g mouse on

# Upgrade $TERM
set -sg escape-time 10
set -g focus-events on
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Start first window at 1
set -g base-index 1
setw -g pane-base-index 1

# Renumber windows when a window is closed
set -g renumber-windows on

# Allow switching between windows using Alt + number key without prefix
bind -r "<" swap-window -d -t -1
bind -r ">" swap-window -d -t +1

# Don't rename window automatically
set-option -g allow-rename off

# Increase scrollback buffer
set -g history-limit 50000

# Bind Prefix to a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Splits keep current path
bind "|" split-window -h -c "#{pane_current_path}"
bind "\\" split-window -fh -c "#{pane_current_path}"
bind "-" split-window -v -c "#{pane_current_path}"
bind "_" split-window -fv -c "#{pane_current_path}"

# Switch pnaes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Reload config
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'dracula/tmux'
set -g @plugin 'jaclu/tmux-menus'

# Continuum / resurrect
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'
set -g @resurrect-capture-pane-contents 'on'

# Dracula
set -g @dracula-show-powerline true
set -g @dracula-plugins "git ssh-session time"
set -g @dracula-refresh-rate 1
set -g @dracula-military-time true
set -g @dracula-time-format "%F %T%z"
set -g @dracula-weather-hide-errors true
set -g @dracula-show-flags true

# Menu
set -g @menus_trigger 'Space'

# Initialize TPM (keep at bottom)
run '~/.tmux/plugins/tpm/tpm'

